language: php

php:
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer install

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php bin/coveralls
