language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

before_script:
    - composer install

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
