language: php

php:
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer install

script:
   - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - php bin/ocular code-coverage:upload --format=php-clover coverage.clover
